#!/usr/bin/env bash

# https://github.com/sobolevn/dotfiles/blob/master/install

set -e

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Linking dotfiles:

run_dotbot() {
	local config
	config="$1"

	"$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
		-d "$BASEDIR" \
		--plugin-dir dotbot-omnipkg \
		-c "$config" $ARGS
}

run_dotbot 'steps/main.yaml' || true
# run_dotbot 'steps/xorg.yaml' || true
# run_dotbot 'steps/vbox.yaml' || true
