- name: My dotfiles config 
  hosts: localhost
  become: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: "Install system packages"
      apt:
        name:
          - git
          - i3
          - zsh
        state: latest
