- name: My dotfiles config 
  hosts: localhost
  become: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: "Install system packages"
      apt:
        name:
          - git
          - i3
          - zsh
          - htop
          - curl
          - ca-certificates
          - jq
        state: latest
    - name: "Install snap packages" 
      community.general.snap:
        name:
          - telegram-desktop
          - bitwarden
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: 
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true
    - name: Install Docker Module for Python
      pip:
        name: docker
