- name: My dotfiles config
  hosts: localhost
  tasks:
    - name: "Install system packages via pacman"
      ansible.builtin.pacman:
        name:
          - git
          - gcc
          - clang
          - i3
          - fish
          - fisher
          - htop
          - curl
          - ca-certificates
          - jq
          - fzf
          - rustup
          - docker
          - docker-compose
          - stow
          - unzip
          - nodejs
          - npm
          - neovim
          - rofi
          - xclip
          - bat
          - cmake
          - make
          - patch
          - lazygit
          - go
          - ripgrep
          - luarocks
          - jdk21-openjdk
          - jdk17-openjdk
          - ruby
          - lua51
          - tree-sitter
          - ttf-jetbrains-mono-nerd
          - php
          - composer
          - keepassxc
          - uv
          - yay
          - picom
          - alacritty
        state: latest
      become: yes
      when: ansible_distribution == "Archlinux"

    - name: "Add the user 'sentyyy' with a fish shell, appending the group 'docker' to the user's groups"
      ansible.builtin.user:
        name: sentyyy
        shell: /usr/bin/fish
        groups: docker
        append: yes
      become: yes

    - name: Get all groups
      ansible.builtin.getent:
        database: group

    - name: "Add user 'sentyyy' to group 'vboxsf' (if exists)"
      ansible.builtin.user:
        name: sentyyy
        groups: vboxsf
        append: yes
      become: yes
      when: ansible_facts.getent_group.get("vboxsf")

    - name: Start SSH agent
      ansible.builtin.systemd_service:
        name: ssh-agent
        enabled: true
        scope: user
        state: started

    - name: Start Docker daemon
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started
      become: yes

    - name: "Install PatrickF1/fzf.fish"
      ansible.builtin.shell: fisher install PatrickF1/fzf.fish
      args:
        executable: /usr/bin/fish

    - name: Create spell directory in nvim directory
      ansible.builtin.file:
        path: ~/.config/nvim/spell/
        state: directory

    - name: Download ru.utf-8.spl
      ansible.builtin.get_url:
        url: http://ftp.vim.org/vim/runtime/spell/ru.utf-8.spl
        dest: ~/.config/nvim/spell/ru.utf-8.spl

    - name: Download ru.utf-8.sug
      ansible.builtin.get_url:
        url: http://ftp.vim.org/vim/runtime/spell/ru.utf-8.sug
        dest: ~/.config/nvim/spell/ru.utf-8.sug

    - name: "Git clone vulhub"
      ansible.builtin.git:
        repo: https://github.com/vulhub/vulhub.git
        dest: "~/utils/vulhub"

    - name: "Git clone SecLists"
      ansible.builtin.git:
        repo: https://github.com/danielmiessler/SecLists.git
        dest: "~/utils/seclists"

    - name: "Git clone docker-compose-lamp"
      ansible.builtin.git:
        repo: https://github.com/sprintcube/docker-compose-lamp.git
        dest: "~/utils/lamp"
